// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_eurasco: dynamic(() => import("./AboutEurasco")),
  hero: dynamic(() => import("./Hero")),
  section_title: dynamic(() => import("./SectionTitle")),
};
